### PR TITLE
Add setup documentation by Claudio Moraes

### PR DESCRIPTION
**Pull request by davidmreed**

### CODE REVIEW

**Comment by davisagli** [comment]
🎉

**Comment by davidmreed** [comment]
W-12595414

**Review by prescod — APPROVED** [review]
I'm sure there's a typo in there somewhere but I think these docs have been reviewed by several people so I kind of spot-checked them for things I know about.

**Comment by davidmreed** [comment]
Yeah, they definitely could use another round of copy-editing, but I think they're delivering value as is.

**Pull request merged**
