### PR TITLE
📦 update cumulusci etc

### PR DESCRIPTION
**Pull request by davisagli**

### CODE REVIEW

**Comment by davisagli** [comment]
@jgerigmeyer what do I need to do to unbreak the yarn install? I wasn't intending to touch frontend stuff at all here.

**Comment by jgerigmeyer** [comment]
@davisagli Ah, it's pulling the `latest` version of the Dockerfile, which we've updated. We've since used tagged versions, but that's not merged upstream yet. I'd think you could update the versions in `package.json`? But I'm okay just merging this and letting CI run on our `master`.

**Comment by jgerigmeyer** [comment]
@davisagli Should this be based on https://github.com/oddbird/Metecho/ instead?

**Comment by davisagli** [comment]
@jgerigmeyer I branched it from there, but submitted the PR to the wrong place. Will try again.

**Pull request closed without merging**
